### PR TITLE
VDX-144 Adjust the SIOPv2 lib documenation with latest changes

### PR DESCRIPTION
**Pull request by maikel-maas**
- Updated README file;

### CODE REVIEW

**Comment by nklomp** [comment]
I hate documents with all kinds of pointers to other documents in Github

**Comment by nklomp** [comment]
I rather have a future documentation website like for VDX, that does proper chapter, headers and links, versus manually linking Markdown files on Github. Not sure how this requirement became part of the ticket

**Review by hrehman-sphereon — APPROVED** [review]

**Review by hrehman-sphereon — CHANGES_REQUESTED** [review]
There are some code example that I will fix.

**Review by sksadjad — COMMENTED** [review]
TBH I don't think we can merge this PR yet. the impl is changing as a result of covering different versions like ID1 and ID11. we also have some additional tickets that will result in further changes in the way we're building OP/RP.

**Review by hrehman-sphereon — APPROVED** [review]
Approving as we just need to merge whatever is currently present.

Agreed with @sksadjad

**Pull request merged**
