### PR TITLE
VDX-138 Check the signature of VC and VPs received in RP side

### PR DESCRIPTION
**Pull request by maikel-maas**
- Added VP verification callback;

### CODE REVIEW

**Review by sksadjad — CHANGES_REQUESTED** [review]
We should be able to configure OP/RP, with 3 options: NEVER, IF_PRESENT, ALWAYS (if not configured-> IF_PRESENT), and based on this value, you'll decide if you want to assert or not

**Comment by nklomp** [comment]
No. VP checks should always be performed

**Review by sksadjad — APPROVED** [review]
looks good to me

**Review by sksadjad — CHANGES_REQUESTED** [review]
build is failing

**Pull request merged**
