### PR TITLE
Dist package fixes

### PR DESCRIPTION
**Pull request by sanderPostma**
Please check if this is an acceptable solution. The way how things are structed in master, since the did-jwt-fork package was added, on the implementing side I need to append /src in every import like this:
import {OP} from "@sphereon/did-auth-siop/dist/main/src"
Moving did-jwt-fork under src solves that issue but then it's mixed with the other packages. I moved those to "main" so the end package looks like this:
image

### CODE REVIEW

**Comment by nklomp** [comment]
Before looking at it first fix the build please

**Comment by nklomp** [comment]
This looks more like a problem with the index.ts or its exports. Do we have our main class properly configured?

**Comment by sanderPostma** [comment]
It is set to dist/main/index.js as it should be, but because of the presence of did-jwt-fork the whole root is moved into the src folder
image
We could also change to this
  "main": "dist/main/src/index.js",
  "types": "dist/main/src/index.d.ts",
But it feels a bit clumsy to have both a dist and a src folder in the artifact path

**Comment by nklomp** [comment]
Ok for now we go ahead, but we need another solutions

**Review by nklomp — APPROVED** [review]

**Pull request merged**
